name: Debug Secret Simple
on:
  push:
    branches:
      - main
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print secret
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BYTES_WORLD__BUSINESS }}"
